all:
	cd src && make
	cp ./src/sudoku ./
	
report: report.pdf

report.pdf: report/report.tex
	@cd report && make report.pdf
	@cp report/report.pdf ./

clean:
	@rm -f src/*.o
	@rm -f sudoku
	@rm -f src/sudoku
	@cd report && make clean
	@rm -f report.pdf


help:
	@echo "Usage:"
	@echo " make [all]	Build"
	@echo " make clean	Remove all files generated by make"
	@echo " make help 	Display this help"

.PHONY: all report clean help